version: '2'
services:
  mariadb:
      image: mariadb:10.0.25
      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
      ports:
          - "3306"
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_USER: "ipay"
          MYSQL_PASSWORD: "ipay"
          MYSQL_DATABASE: "ipay"
      networks:
          - main-network
  redis:
      image: redis
      ports:
          - "6379"
      networks:
           - main-network
networks:
  main-network:
    driver: bridge
